name: Build

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22

      - name: Build for Linux
        run: go build -o ./bin/ci-mailer-linux

      - name: Build for Windows
        run: GOOS=windows GOARCH=amd64 go build -o ./bin/ci-mailer.exe

      - name: Build for macOS
        run: GOOS=darwin GOARCH=amd64 go build -o ./bin/ci-mailer

      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ci-mailer-builds
          path: bin


          

