name: Build

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                    go-version: 1.22

            - name: Build
              run: go build -o 

            - name: Archive artifacts
              uses: actions/upload-artifact@v2
              with:
                    name: myprogram
                    path: myprogram