name: Build

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22

      - name: Install dependencies
        run: go get .

      - name: Test with the Go CLI
        run: go test

      - name: Build for Linux
        run: go build -o ./bin/ci-mailer-linux

      - name: Build for Windows
        run: GOOS=windows GOARCH=amd64 go build -o ./bin/ci-mailer.exe

      - name: Build for macOS
        run: GOOS=darwin GOARCH=amd64 go build -o ./bin/ci-mailer

      - name: Build and Release
        uses: softprops/action-gh-release@v2.3.1  # Adjust version as needed
        with:
          tag_name: ${{ github.ref }} 
          files: ./bin/*  
          #

